<a href="https://colab.research.google.com/github/applejxd/colaboratory/blob/master/ml/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow テンソル操作メモ

[TensorFlow メソッド、shape をいじる系メモ](https://qiita.com/cfiken/items/04925d4da39e1a24114e)

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
a_tensor = tf.random.uniform(shape=[4, 2, 3], minval=-10, maxval=10, dtype=tf.float64)
a_tensor

<tf.Tensor: shape=(4, 2, 3), dtype=float64, numpy=
array([[[-4.91963095, -4.66853684,  8.81406452],
        [ 4.74523416,  9.70933287, -7.63327008]],

       [[-7.96193703, -8.5054882 , -2.74834238],
        [ 3.98221438,  7.87066089,  0.65405054]],

       [[-8.13854054,  3.60798422,  0.0287366 ],
        [-7.06542367, -3.03645089, -7.31469691]],

       [[ 5.63056176, -5.707417  ,  4.07563791],
        [-9.33349076, -2.45003457,  8.41547415]]])>

In [3]:
tf.shape(a_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>

In [4]:
b_tensor = tf.constant([[[1, 3, 5], [7, 11, 13]]], dtype=tf.float64)
b_tensor

<tf.Tensor: shape=(1, 2, 3), dtype=float64, numpy=
array([[[ 1.,  3.,  5.],
        [ 7., 11., 13.]]])>

## 変形する

In [5]:
# 合計サイズが 3x5x2 となるように変形する必要がある
tf.reshape(a_tensor, shape=(-1, 3, 2))

<tf.Tensor: shape=(4, 3, 2), dtype=float64, numpy=
array([[[-4.91963095, -4.66853684],
        [ 8.81406452,  4.74523416],
        [ 9.70933287, -7.63327008]],

       [[-7.96193703, -8.5054882 ],
        [-2.74834238,  3.98221438],
        [ 7.87066089,  0.65405054]],

       [[-8.13854054,  3.60798422],
        [ 0.0287366 , -7.06542367],
        [-3.03645089, -7.31469691]],

       [[ 5.63056176, -5.707417  ],
        [ 4.07563791, -9.33349076],
        [-2.45003457,  8.41547415]]])>

## 拡大する

### 次元(添字)を増やす

In [6]:
tf.expand_dims(a_tensor, axis=2)

<tf.Tensor: shape=(4, 2, 1, 3), dtype=float64, numpy=
array([[[[-4.91963095, -4.66853684,  8.81406452]],

        [[ 4.74523416,  9.70933287, -7.63327008]]],


       [[[-7.96193703, -8.5054882 , -2.74834238]],

        [[ 3.98221438,  7.87066089,  0.65405054]]],


       [[[-8.13854054,  3.60798422,  0.0287366 ]],

        [[-7.06542367, -3.03645089, -7.31469691]]],


       [[[ 5.63056176, -5.707417  ,  4.07563791]],

        [[-9.33349076, -2.45003457,  8.41547415]]]])>

### パディングする

In [7]:
tf.pad(a_tensor, paddings=[[0,0],[0,0],[0,1]])

<tf.Tensor: shape=(4, 2, 4), dtype=float64, numpy=
array([[[-4.91963095, -4.66853684,  8.81406452,  0.        ],
        [ 4.74523416,  9.70933287, -7.63327008,  0.        ]],

       [[-7.96193703, -8.5054882 , -2.74834238,  0.        ],
        [ 3.98221438,  7.87066089,  0.65405054,  0.        ]],

       [[-8.13854054,  3.60798422,  0.0287366 ,  0.        ],
        [-7.06542367, -3.03645089, -7.31469691,  0.        ]],

       [[ 5.63056176, -5.707417  ,  4.07563791,  0.        ],
        [-9.33349076, -2.45003457,  8.41547415,  0.        ]]])>

## 繰り返す

### 次元(添字)を増やさず繰り返す

In [8]:
tf.tile(a_tensor, multiples=(1,1,2))

<tf.Tensor: shape=(4, 2, 6), dtype=float64, numpy=
array([[[-4.91963095, -4.66853684,  8.81406452, -4.91963095,
         -4.66853684,  8.81406452],
        [ 4.74523416,  9.70933287, -7.63327008,  4.74523416,
          9.70933287, -7.63327008]],

       [[-7.96193703, -8.5054882 , -2.74834238, -7.96193703,
         -8.5054882 , -2.74834238],
        [ 3.98221438,  7.87066089,  0.65405054,  3.98221438,
          7.87066089,  0.65405054]],

       [[-8.13854054,  3.60798422,  0.0287366 , -8.13854054,
          3.60798422,  0.0287366 ],
        [-7.06542367, -3.03645089, -7.31469691, -7.06542367,
         -3.03645089, -7.31469691]],

       [[ 5.63056176, -5.707417  ,  4.07563791,  5.63056176,
         -5.707417  ,  4.07563791],
        [-9.33349076, -2.45003457,  8.41547415, -9.33349076,
         -2.45003457,  8.41547415]]])>

\begin{equation}
    b_{ijkl} = (a_{jkl} a_{jkl})
\end{equation}

### 次元(添字)を増やして繰り返す

In [9]:
tf.tile(tf.expand_dims(a_tensor, 0), [2, 1, 1, 1]) 

<tf.Tensor: shape=(2, 4, 2, 3), dtype=float64, numpy=
array([[[[-4.91963095, -4.66853684,  8.81406452],
         [ 4.74523416,  9.70933287, -7.63327008]],

        [[-7.96193703, -8.5054882 , -2.74834238],
         [ 3.98221438,  7.87066089,  0.65405054]],

        [[-8.13854054,  3.60798422,  0.0287366 ],
         [-7.06542367, -3.03645089, -7.31469691]],

        [[ 5.63056176, -5.707417  ,  4.07563791],
         [-9.33349076, -2.45003457,  8.41547415]]],


       [[[-4.91963095, -4.66853684,  8.81406452],
         [ 4.74523416,  9.70933287, -7.63327008]],

        [[-7.96193703, -8.5054882 , -2.74834238],
         [ 3.98221438,  7.87066089,  0.65405054]],

        [[-8.13854054,  3.60798422,  0.0287366 ],
         [-7.06542367, -3.03645089, -7.31469691]],

        [[ 5.63056176, -5.707417  ,  4.07563791],
         [-9.33349076, -2.45003457,  8.41547415]]]])>

## 分割する

In [10]:
tf.split(a_tensor, num_or_size_splits=[-1, 1], axis=2)

[<tf.Tensor: shape=(4, 2, 2), dtype=float64, numpy=
 array([[[-4.91963095, -4.66853684],
         [ 4.74523416,  9.70933287]],
 
        [[-7.96193703, -8.5054882 ],
         [ 3.98221438,  7.87066089]],
 
        [[-8.13854054,  3.60798422],
         [-7.06542367, -3.03645089]],
 
        [[ 5.63056176, -5.707417  ],
         [-9.33349076, -2.45003457]]])>,
 <tf.Tensor: shape=(4, 2, 1), dtype=float64, numpy=
 array([[[ 8.81406452],
         [-7.63327008]],
 
        [[-2.74834238],
         [ 0.65405054]],
 
        [[ 0.0287366 ],
         [-7.31469691]],
 
        [[ 4.07563791],
         [ 8.41547415]]])>]

## 結合する

### 次元(添字)を増やさず結合する

以下の条件が必要:
- 型が一致している
- 結合する axis 以外が一致している

In [11]:
tf.concat([a_tensor, b_tensor], axis=0)

<tf.Tensor: shape=(5, 2, 3), dtype=float64, numpy=
array([[[-4.91963095, -4.66853684,  8.81406452],
        [ 4.74523416,  9.70933287, -7.63327008]],

       [[-7.96193703, -8.5054882 , -2.74834238],
        [ 3.98221438,  7.87066089,  0.65405054]],

       [[-8.13854054,  3.60798422,  0.0287366 ],
        [-7.06542367, -3.03645089, -7.31469691]],

       [[ 5.63056176, -5.707417  ,  4.07563791],
        [-9.33349076, -2.45003457,  8.41547415]],

       [[ 1.        ,  3.        ,  5.        ],
        [ 7.        , 11.        , 13.        ]]])>

## 縮小する

ｔｆ.extend_dim の逆は tf.squeeze

In [12]:
tf.squeeze(tf.expand_dims(a_tensor, axis=2))

<tf.Tensor: shape=(4, 2, 3), dtype=float64, numpy=
array([[[-4.91963095, -4.66853684,  8.81406452],
        [ 4.74523416,  9.70933287, -7.63327008]],

       [[-7.96193703, -8.5054882 , -2.74834238],
        [ 3.98221438,  7.87066089,  0.65405054]],

       [[-8.13854054,  3.60798422,  0.0287366 ],
        [-7.06542367, -3.03645089, -7.31469691]],

       [[ 5.63056176, -5.707417  ,  4.07563791],
        [-9.33349076, -2.45003457,  8.41547415]]])>