<a href="https://colab.research.google.com/github/applejxd/colaboratory/blob/master/ml/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow テンソル操作メモ

[TensorFlow メソッド、shape をいじる系メモ](https://qiita.com/cfiken/items/04925d4da39e1a24114e)

In [135]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [136]:
a_tensor = tf.random.uniform(shape=[4, 2, 3], minval=-10, maxval=10, dtype=tf.float64)
a_tensor

<tf.Tensor: shape=(4, 2, 3), dtype=float64, numpy=
array([[[-0.97107534, -9.71347533, -3.5854277 ],
        [ 0.84162925,  6.47108725,  7.69971562]],

       [[-8.38022846, -4.35354346, -2.24024079],
        [ 9.71530559, -7.27968402, -9.03988732]],

       [[-6.33562056,  3.1541116 ,  8.40375905],
        [ 7.5423454 ,  1.25421169, -8.83770458]],

       [[ 5.31751367,  0.07312144,  3.0733425 ],
        [ 5.97940871,  1.98106017, -5.06841261]]])>

In [137]:
tf.shape(a_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>

In [138]:
b_tensor = tf.constant([[[1, 3, 5], [7, 11, 13]]], dtype=tf.float64)
b_tensor

<tf.Tensor: shape=(1, 2, 3), dtype=float64, numpy=
array([[[ 1.,  3.,  5.],
        [ 7., 11., 13.]]])>

## 変形する

In [139]:
# 合計サイズが 3x5x2 となるように変形する必要がある
tf.reshape(a_tensor, shape=(-1, 3, 2))

<tf.Tensor: shape=(4, 3, 2), dtype=float64, numpy=
array([[[-0.97107534, -9.71347533],
        [-3.5854277 ,  0.84162925],
        [ 6.47108725,  7.69971562]],

       [[-8.38022846, -4.35354346],
        [-2.24024079,  9.71530559],
        [-7.27968402, -9.03988732]],

       [[-6.33562056,  3.1541116 ],
        [ 8.40375905,  7.5423454 ],
        [ 1.25421169, -8.83770458]],

       [[ 5.31751367,  0.07312144],
        [ 3.0733425 ,  5.97940871],
        [ 1.98106017, -5.06841261]]])>

## 拡大する

### 次元(添字)を増やす

In [140]:
tf.expand_dims(a_tensor, axis=2)

<tf.Tensor: shape=(4, 2, 1, 3), dtype=float64, numpy=
array([[[[-0.97107534, -9.71347533, -3.5854277 ]],

        [[ 0.84162925,  6.47108725,  7.69971562]]],


       [[[-8.38022846, -4.35354346, -2.24024079]],

        [[ 9.71530559, -7.27968402, -9.03988732]]],


       [[[-6.33562056,  3.1541116 ,  8.40375905]],

        [[ 7.5423454 ,  1.25421169, -8.83770458]]],


       [[[ 5.31751367,  0.07312144,  3.0733425 ]],

        [[ 5.97940871,  1.98106017, -5.06841261]]]])>

### パディングする

In [141]:
tf.pad(a_tensor, paddings=[[0,0],[0,0],[0,1]])

<tf.Tensor: shape=(4, 2, 4), dtype=float64, numpy=
array([[[-0.97107534, -9.71347533, -3.5854277 ,  0.        ],
        [ 0.84162925,  6.47108725,  7.69971562,  0.        ]],

       [[-8.38022846, -4.35354346, -2.24024079,  0.        ],
        [ 9.71530559, -7.27968402, -9.03988732,  0.        ]],

       [[-6.33562056,  3.1541116 ,  8.40375905,  0.        ],
        [ 7.5423454 ,  1.25421169, -8.83770458,  0.        ]],

       [[ 5.31751367,  0.07312144,  3.0733425 ,  0.        ],
        [ 5.97940871,  1.98106017, -5.06841261,  0.        ]]])>

## 繰り返す

### 次元(添字)を増やさず繰り返す

In [142]:
tf.tile(a_tensor, multiples=(1,1,2))

<tf.Tensor: shape=(4, 2, 6), dtype=float64, numpy=
array([[[-0.97107534, -9.71347533, -3.5854277 , -0.97107534,
         -9.71347533, -3.5854277 ],
        [ 0.84162925,  6.47108725,  7.69971562,  0.84162925,
          6.47108725,  7.69971562]],

       [[-8.38022846, -4.35354346, -2.24024079, -8.38022846,
         -4.35354346, -2.24024079],
        [ 9.71530559, -7.27968402, -9.03988732,  9.71530559,
         -7.27968402, -9.03988732]],

       [[-6.33562056,  3.1541116 ,  8.40375905, -6.33562056,
          3.1541116 ,  8.40375905],
        [ 7.5423454 ,  1.25421169, -8.83770458,  7.5423454 ,
          1.25421169, -8.83770458]],

       [[ 5.31751367,  0.07312144,  3.0733425 ,  5.31751367,
          0.07312144,  3.0733425 ],
        [ 5.97940871,  1.98106017, -5.06841261,  5.97940871,
          1.98106017, -5.06841261]]])>

\begin{equation}
    b_{ijkl} = (a_{jkl} a_{jkl})
\end{equation}

### 次元(添字)を増やして繰り返す

In [143]:
tf.tile(tf.expand_dims(a_tensor, 0), [2, 1, 1, 1]) 

<tf.Tensor: shape=(2, 4, 2, 3), dtype=float64, numpy=
array([[[[-0.97107534, -9.71347533, -3.5854277 ],
         [ 0.84162925,  6.47108725,  7.69971562]],

        [[-8.38022846, -4.35354346, -2.24024079],
         [ 9.71530559, -7.27968402, -9.03988732]],

        [[-6.33562056,  3.1541116 ,  8.40375905],
         [ 7.5423454 ,  1.25421169, -8.83770458]],

        [[ 5.31751367,  0.07312144,  3.0733425 ],
         [ 5.97940871,  1.98106017, -5.06841261]]],


       [[[-0.97107534, -9.71347533, -3.5854277 ],
         [ 0.84162925,  6.47108725,  7.69971562]],

        [[-8.38022846, -4.35354346, -2.24024079],
         [ 9.71530559, -7.27968402, -9.03988732]],

        [[-6.33562056,  3.1541116 ,  8.40375905],
         [ 7.5423454 ,  1.25421169, -8.83770458]],

        [[ 5.31751367,  0.07312144,  3.0733425 ],
         [ 5.97940871,  1.98106017, -5.06841261]]]])>

## 分割する

In [144]:
tf.split(a_tensor, [2, 1], 2)

[<tf.Tensor: shape=(4, 2, 2), dtype=float64, numpy=
 array([[[-0.97107534, -9.71347533],
         [ 0.84162925,  6.47108725]],
 
        [[-8.38022846, -4.35354346],
         [ 9.71530559, -7.27968402]],
 
        [[-6.33562056,  3.1541116 ],
         [ 7.5423454 ,  1.25421169]],
 
        [[ 5.31751367,  0.07312144],
         [ 5.97940871,  1.98106017]]])>,
 <tf.Tensor: shape=(4, 2, 1), dtype=float64, numpy=
 array([[[-3.5854277 ],
         [ 7.69971562]],
 
        [[-2.24024079],
         [-9.03988732]],
 
        [[ 8.40375905],
         [-8.83770458]],
 
        [[ 3.0733425 ],
         [-5.06841261]]])>]

## 結合する

### 次元(添字)を増やさず結合する

以下の条件が必要:
- 型が一致している
- 結合する axis 以外が一致している

In [145]:
tf.concat([a_tensor, b_tensor], axis=0)

<tf.Tensor: shape=(5, 2, 3), dtype=float64, numpy=
array([[[-0.97107534, -9.71347533, -3.5854277 ],
        [ 0.84162925,  6.47108725,  7.69971562]],

       [[-8.38022846, -4.35354346, -2.24024079],
        [ 9.71530559, -7.27968402, -9.03988732]],

       [[-6.33562056,  3.1541116 ,  8.40375905],
        [ 7.5423454 ,  1.25421169, -8.83770458]],

       [[ 5.31751367,  0.07312144,  3.0733425 ],
        [ 5.97940871,  1.98106017, -5.06841261]],

       [[ 1.        ,  3.        ,  5.        ],
        [ 7.        , 11.        , 13.        ]]])>

## 縮小する

ｔｆ.extend_dim の逆は tf.squeeze

In [146]:
tf.squeeze(tf.expand_dims(a_tensor, axis=2))

<tf.Tensor: shape=(4, 2, 3), dtype=float64, numpy=
array([[[-0.97107534, -9.71347533, -3.5854277 ],
        [ 0.84162925,  6.47108725,  7.69971562]],

       [[-8.38022846, -4.35354346, -2.24024079],
        [ 9.71530559, -7.27968402, -9.03988732]],

       [[-6.33562056,  3.1541116 ,  8.40375905],
        [ 7.5423454 ,  1.25421169, -8.83770458]],

       [[ 5.31751367,  0.07312144,  3.0733425 ],
        [ 5.97940871,  1.98106017, -5.06841261]]])>