<a href="https://colab.research.google.com/github/applejxd/colaboratory/blob/master/ml/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow テンソル操作メモ

[TensorFlow メソッド、shape をいじる系メモ](https://qiita.com/cfiken/items/04925d4da39e1a24114e)

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [6]:
a_tensor = tf.random.uniform(shape=[3, 5, 2], minval=-10, maxval=10, dtype=tf.float64)
a_tensor

<tf.Tensor: shape=(3, 5, 2), dtype=float64, numpy=
array([[[ 1.93958273,  2.47649068],
        [-2.68770597, -9.37096954],
        [ 0.86441707,  3.58717915],
        [-1.70364915,  5.74635864],
        [ 2.19768924,  0.43933695]],

       [[ 4.22154174, -9.6846359 ],
        [ 7.75456721,  7.88153707],
        [ 0.4655373 , -0.62459365],
        [-7.74720726,  0.20680975],
        [ 5.31531865,  4.30025464]],

       [[-1.80344762,  6.7775036 ],
        [-9.12488846,  8.33154901],
        [ 9.59081269, -6.7596981 ],
        [ 5.4673734 ,  6.01628773],
        [ 6.87358599, -6.45304105]]])>

In [14]:
tf.tile(a_tensor, multiples=(1,1,2))

<tf.Tensor: shape=(3, 5, 4), dtype=float64, numpy=
array([[[ 1.93958273,  2.47649068,  1.93958273,  2.47649068],
        [-2.68770597, -9.37096954, -2.68770597, -9.37096954],
        [ 0.86441707,  3.58717915,  0.86441707,  3.58717915],
        [-1.70364915,  5.74635864, -1.70364915,  5.74635864],
        [ 2.19768924,  0.43933695,  2.19768924,  0.43933695]],

       [[ 4.22154174, -9.6846359 ,  4.22154174, -9.6846359 ],
        [ 7.75456721,  7.88153707,  7.75456721,  7.88153707],
        [ 0.4655373 , -0.62459365,  0.4655373 , -0.62459365],
        [-7.74720726,  0.20680975, -7.74720726,  0.20680975],
        [ 5.31531865,  4.30025464,  5.31531865,  4.30025464]],

       [[-1.80344762,  6.7775036 , -1.80344762,  6.7775036 ],
        [-9.12488846,  8.33154901, -9.12488846,  8.33154901],
        [ 9.59081269, -6.7596981 ,  9.59081269, -6.7596981 ],
        [ 5.4673734 ,  6.01628773,  5.4673734 ,  6.01628773],
        [ 6.87358599, -6.45304105,  6.87358599, -6.45304105]]])>

In [19]:
tf.expand_dims(a_tensor, axis=2)

<tf.Tensor: shape=(3, 5, 1, 2), dtype=float64, numpy=
array([[[[ 1.93958273,  2.47649068]],

        [[-2.68770597, -9.37096954]],

        [[ 0.86441707,  3.58717915]],

        [[-1.70364915,  5.74635864]],

        [[ 2.19768924,  0.43933695]]],


       [[[ 4.22154174, -9.6846359 ]],

        [[ 7.75456721,  7.88153707]],

        [[ 0.4655373 , -0.62459365]],

        [[-7.74720726,  0.20680975]],

        [[ 5.31531865,  4.30025464]]],


       [[[-1.80344762,  6.7775036 ]],

        [[-9.12488846,  8.33154901]],

        [[ 9.59081269, -6.7596981 ]],

        [[ 5.4673734 ,  6.01628773]],

        [[ 6.87358599, -6.45304105]]]])>

In [21]:
# 合計サイズが 3x5x2 となるように変形する必要がある
tf.reshape(a_tensor, shape=(-1, 3, 2))

<tf.Tensor: shape=(5, 3, 2), dtype=float64, numpy=
array([[[ 1.93958273,  2.47649068],
        [-2.68770597, -9.37096954],
        [ 0.86441707,  3.58717915]],

       [[-1.70364915,  5.74635864],
        [ 2.19768924,  0.43933695],
        [ 4.22154174, -9.6846359 ]],

       [[ 7.75456721,  7.88153707],
        [ 0.4655373 , -0.62459365],
        [-7.74720726,  0.20680975]],

       [[ 5.31531865,  4.30025464],
        [-1.80344762,  6.7775036 ],
        [-9.12488846,  8.33154901]],

       [[ 9.59081269, -6.7596981 ],
        [ 5.4673734 ,  6.01628773],
        [ 6.87358599, -6.45304105]]])>