<a href="https://colab.research.google.com/github/applejxd/colaboratory/blob/master/ml/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow テンソル操作メモ

[TensorFlow メソッド、shape をいじる系メモ](https://qiita.com/cfiken/items/04925d4da39e1a24114e)

In [19]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [20]:
a_tensor = tf.random.uniform(shape=[3, 4, 2], minval=-10, maxval=10, dtype=tf.float64)
a_tensor

<tf.Tensor: shape=(3, 4, 2), dtype=float64, numpy=
array([[[ 1.47630569,  4.43977872],
        [-7.43028114, -0.80163526],
        [-9.95360956,  3.06618057],
        [-9.4019737 , -1.51439202]],

       [[-9.47173424,  6.68559221],
        [ 5.9331059 , -6.34907511],
        [-2.93324985,  5.0203594 ],
        [ 9.0118155 ,  9.76772985]],

       [[ 8.34078037,  5.23837545],
        [ 4.70718525, -3.4766256 ],
        [ 0.34922764,  3.16928852],
        [-4.51750996,  0.02442664]]])>

In [21]:
tf.shape(a_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 2], dtype=int32)>

## 変形する

In [22]:
# 合計サイズが 3x5x2 となるように変形する必要がある
tf.reshape(a_tensor, shape=(-1, 3, 2))

<tf.Tensor: shape=(4, 3, 2), dtype=float64, numpy=
array([[[ 1.47630569,  4.43977872],
        [-7.43028114, -0.80163526],
        [-9.95360956,  3.06618057]],

       [[-9.4019737 , -1.51439202],
        [-9.47173424,  6.68559221],
        [ 5.9331059 , -6.34907511]],

       [[-2.93324985,  5.0203594 ],
        [ 9.0118155 ,  9.76772985],
        [ 8.34078037,  5.23837545]],

       [[ 4.70718525, -3.4766256 ],
        [ 0.34922764,  3.16928852],
        [-4.51750996,  0.02442664]]])>

## 拡大する

### 次元(添字)を増やす

In [23]:
tf.expand_dims(a_tensor, axis=2)

<tf.Tensor: shape=(3, 4, 1, 2), dtype=float64, numpy=
array([[[[ 1.47630569,  4.43977872]],

        [[-7.43028114, -0.80163526]],

        [[-9.95360956,  3.06618057]],

        [[-9.4019737 , -1.51439202]]],


       [[[-9.47173424,  6.68559221]],

        [[ 5.9331059 , -6.34907511]],

        [[-2.93324985,  5.0203594 ]],

        [[ 9.0118155 ,  9.76772985]]],


       [[[ 8.34078037,  5.23837545]],

        [[ 4.70718525, -3.4766256 ]],

        [[ 0.34922764,  3.16928852]],

        [[-4.51750996,  0.02442664]]]])>

### パディングする

In [24]:
tf.pad(a_tensor, paddings=[[0,0],[0,0],[0,1]])

<tf.Tensor: shape=(3, 4, 3), dtype=float64, numpy=
array([[[ 1.47630569,  4.43977872,  0.        ],
        [-7.43028114, -0.80163526,  0.        ],
        [-9.95360956,  3.06618057,  0.        ],
        [-9.4019737 , -1.51439202,  0.        ]],

       [[-9.47173424,  6.68559221,  0.        ],
        [ 5.9331059 , -6.34907511,  0.        ],
        [-2.93324985,  5.0203594 ,  0.        ],
        [ 9.0118155 ,  9.76772985,  0.        ]],

       [[ 8.34078037,  5.23837545,  0.        ],
        [ 4.70718525, -3.4766256 ,  0.        ],
        [ 0.34922764,  3.16928852,  0.        ],
        [-4.51750996,  0.02442664,  0.        ]]])>

## 繰り返す

### 次元(添字)を増やさず繰り返す

In [25]:
tf.tile(a_tensor, multiples=(1,1,2))

<tf.Tensor: shape=(3, 4, 4), dtype=float64, numpy=
array([[[ 1.47630569,  4.43977872,  1.47630569,  4.43977872],
        [-7.43028114, -0.80163526, -7.43028114, -0.80163526],
        [-9.95360956,  3.06618057, -9.95360956,  3.06618057],
        [-9.4019737 , -1.51439202, -9.4019737 , -1.51439202]],

       [[-9.47173424,  6.68559221, -9.47173424,  6.68559221],
        [ 5.9331059 , -6.34907511,  5.9331059 , -6.34907511],
        [-2.93324985,  5.0203594 , -2.93324985,  5.0203594 ],
        [ 9.0118155 ,  9.76772985,  9.0118155 ,  9.76772985]],

       [[ 8.34078037,  5.23837545,  8.34078037,  5.23837545],
        [ 4.70718525, -3.4766256 ,  4.70718525, -3.4766256 ],
        [ 0.34922764,  3.16928852,  0.34922764,  3.16928852],
        [-4.51750996,  0.02442664, -4.51750996,  0.02442664]]])>

\begin{equation}
    b_{ijkl} = (a_{jkl} a_{jkl})
\end{equation}

### 次元(添字)を増やして繰り返す

In [26]:
tf.tile(tf.expand_dims(a_tensor, 0), [2, 1, 1, 1]) 

<tf.Tensor: shape=(2, 3, 4, 2), dtype=float64, numpy=
array([[[[ 1.47630569,  4.43977872],
         [-7.43028114, -0.80163526],
         [-9.95360956,  3.06618057],
         [-9.4019737 , -1.51439202]],

        [[-9.47173424,  6.68559221],
         [ 5.9331059 , -6.34907511],
         [-2.93324985,  5.0203594 ],
         [ 9.0118155 ,  9.76772985]],

        [[ 8.34078037,  5.23837545],
         [ 4.70718525, -3.4766256 ],
         [ 0.34922764,  3.16928852],
         [-4.51750996,  0.02442664]]],


       [[[ 1.47630569,  4.43977872],
         [-7.43028114, -0.80163526],
         [-9.95360956,  3.06618057],
         [-9.4019737 , -1.51439202]],

        [[-9.47173424,  6.68559221],
         [ 5.9331059 , -6.34907511],
         [-2.93324985,  5.0203594 ],
         [ 9.0118155 ,  9.76772985]],

        [[ 8.34078037,  5.23837545],
         [ 4.70718525, -3.4766256 ],
         [ 0.34922764,  3.16928852],
         [-4.51750996,  0.02442664]]]])>

## 分割する

In [29]:
tf.split(a_tensor, [1, 1], 2)

[<tf.Tensor: shape=(3, 4, 1), dtype=float64, numpy=
 array([[[ 1.47630569],
         [-7.43028114],
         [-9.95360956],
         [-9.4019737 ]],
 
        [[-9.47173424],
         [ 5.9331059 ],
         [-2.93324985],
         [ 9.0118155 ]],
 
        [[ 8.34078037],
         [ 4.70718525],
         [ 0.34922764],
         [-4.51750996]]])>, <tf.Tensor: shape=(3, 4, 1), dtype=float64, numpy=
 array([[[ 4.43977872],
         [-0.80163526],
         [ 3.06618057],
         [-1.51439202]],
 
        [[ 6.68559221],
         [-6.34907511],
         [ 5.0203594 ],
         [ 9.76772985]],
 
        [[ 5.23837545],
         [-3.4766256 ],
         [ 3.16928852],
         [ 0.02442664]]])>]

## 縮小する

ｔｆ.extend_dim の逆は tf.squeeze

In [30]:
tf.squeeze(tf.expand_dims(a_tensor, axis=2))

<tf.Tensor: shape=(3, 4, 2), dtype=float64, numpy=
array([[[ 1.47630569,  4.43977872],
        [-7.43028114, -0.80163526],
        [-9.95360956,  3.06618057],
        [-9.4019737 , -1.51439202]],

       [[-9.47173424,  6.68559221],
        [ 5.9331059 , -6.34907511],
        [-2.93324985,  5.0203594 ],
        [ 9.0118155 ,  9.76772985]],

       [[ 8.34078037,  5.23837545],
        [ 4.70718525, -3.4766256 ],
        [ 0.34922764,  3.16928852],
        [-4.51750996,  0.02442664]]])>