<a href="https://colab.research.google.com/github/applejxd/colaboratory/blob/master/ml/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow テンソル操作メモ

[TensorFlow メソッド、shape をいじる系メモ](https://qiita.com/cfiken/items/04925d4da39e1a24114e)

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
a_tensor = tf.random.uniform(shape=[4, 2, 3], minval=-10, maxval=10, dtype=tf.float64)
a_tensor

<tf.Tensor: shape=(4, 2, 3), dtype=float64, numpy=
array([[[ 1.73369404,  2.11681321, -5.86720335],
        [-4.38655271, -2.11421878, -9.61098953]],

       [[-5.71577344, -8.67702183,  8.54644893],
        [-3.22580896, -2.9048623 , -6.15847763]],

       [[ 1.28737215, -6.51552529, -9.22646899],
        [-9.92081893, -1.05985511, -5.39704617]],

       [[ 8.53265156,  1.65726111,  9.79532013],
        [ 3.21406123, -9.45604106, -1.55242791]]])>

In [3]:
tf.shape(a_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>

In [4]:
b_tensor = tf.constant([[[1, 3, 5], [7, 11, 13]]], dtype=tf.float64)
b_tensor

<tf.Tensor: shape=(1, 2, 3), dtype=float64, numpy=
array([[[ 1.,  3.,  5.],
        [ 7., 11., 13.]]])>

## 変形する

In [5]:
# 合計サイズが 3x5x2 となるように変形する必要がある
tf.reshape(a_tensor, shape=(-1, 3, 2))

<tf.Tensor: shape=(4, 3, 2), dtype=float64, numpy=
array([[[ 1.73369404,  2.11681321],
        [-5.86720335, -4.38655271],
        [-2.11421878, -9.61098953]],

       [[-5.71577344, -8.67702183],
        [ 8.54644893, -3.22580896],
        [-2.9048623 , -6.15847763]],

       [[ 1.28737215, -6.51552529],
        [-9.22646899, -9.92081893],
        [-1.05985511, -5.39704617]],

       [[ 8.53265156,  1.65726111],
        [ 9.79532013,  3.21406123],
        [-9.45604106, -1.55242791]]])>

## 拡大する

### 次元(添字)を増やす

In [6]:
tf.expand_dims(a_tensor, axis=2)

<tf.Tensor: shape=(4, 2, 1, 3), dtype=float64, numpy=
array([[[[ 1.73369404,  2.11681321, -5.86720335]],

        [[-4.38655271, -2.11421878, -9.61098953]]],


       [[[-5.71577344, -8.67702183,  8.54644893]],

        [[-3.22580896, -2.9048623 , -6.15847763]]],


       [[[ 1.28737215, -6.51552529, -9.22646899]],

        [[-9.92081893, -1.05985511, -5.39704617]]],


       [[[ 8.53265156,  1.65726111,  9.79532013]],

        [[ 3.21406123, -9.45604106, -1.55242791]]]])>

### パディングする

In [7]:
tf.pad(a_tensor, paddings=[[0,0],[0,0],[0,1]])

<tf.Tensor: shape=(4, 2, 4), dtype=float64, numpy=
array([[[ 1.73369404,  2.11681321, -5.86720335,  0.        ],
        [-4.38655271, -2.11421878, -9.61098953,  0.        ]],

       [[-5.71577344, -8.67702183,  8.54644893,  0.        ],
        [-3.22580896, -2.9048623 , -6.15847763,  0.        ]],

       [[ 1.28737215, -6.51552529, -9.22646899,  0.        ],
        [-9.92081893, -1.05985511, -5.39704617,  0.        ]],

       [[ 8.53265156,  1.65726111,  9.79532013,  0.        ],
        [ 3.21406123, -9.45604106, -1.55242791,  0.        ]]])>

## 繰り返す

### 次元(添字)を増やさず繰り返す

In [8]:
tf.tile(a_tensor, multiples=(1,1,2))

<tf.Tensor: shape=(4, 2, 6), dtype=float64, numpy=
array([[[ 1.73369404,  2.11681321, -5.86720335,  1.73369404,
          2.11681321, -5.86720335],
        [-4.38655271, -2.11421878, -9.61098953, -4.38655271,
         -2.11421878, -9.61098953]],

       [[-5.71577344, -8.67702183,  8.54644893, -5.71577344,
         -8.67702183,  8.54644893],
        [-3.22580896, -2.9048623 , -6.15847763, -3.22580896,
         -2.9048623 , -6.15847763]],

       [[ 1.28737215, -6.51552529, -9.22646899,  1.28737215,
         -6.51552529, -9.22646899],
        [-9.92081893, -1.05985511, -5.39704617, -9.92081893,
         -1.05985511, -5.39704617]],

       [[ 8.53265156,  1.65726111,  9.79532013,  8.53265156,
          1.65726111,  9.79532013],
        [ 3.21406123, -9.45604106, -1.55242791,  3.21406123,
         -9.45604106, -1.55242791]]])>

\begin{equation}
    b_{ijkl} = (a_{jkl} a_{jkl})
\end{equation}

### 次元(添字)を増やして繰り返す

In [9]:
tf.tile(tf.expand_dims(a_tensor, 0), [2, 1, 1, 1]) 

<tf.Tensor: shape=(2, 4, 2, 3), dtype=float64, numpy=
array([[[[ 1.73369404,  2.11681321, -5.86720335],
         [-4.38655271, -2.11421878, -9.61098953]],

        [[-5.71577344, -8.67702183,  8.54644893],
         [-3.22580896, -2.9048623 , -6.15847763]],

        [[ 1.28737215, -6.51552529, -9.22646899],
         [-9.92081893, -1.05985511, -5.39704617]],

        [[ 8.53265156,  1.65726111,  9.79532013],
         [ 3.21406123, -9.45604106, -1.55242791]]],


       [[[ 1.73369404,  2.11681321, -5.86720335],
         [-4.38655271, -2.11421878, -9.61098953]],

        [[-5.71577344, -8.67702183,  8.54644893],
         [-3.22580896, -2.9048623 , -6.15847763]],

        [[ 1.28737215, -6.51552529, -9.22646899],
         [-9.92081893, -1.05985511, -5.39704617]],

        [[ 8.53265156,  1.65726111,  9.79532013],
         [ 3.21406123, -9.45604106, -1.55242791]]]])>

## 分割する

In [10]:
tf.split(a_tensor, num_or_size_splits=[-1, 1], axis=-1)

[<tf.Tensor: shape=(4, 2, 2), dtype=float64, numpy=
 array([[[ 1.73369404,  2.11681321],
         [-4.38655271, -2.11421878]],
 
        [[-5.71577344, -8.67702183],
         [-3.22580896, -2.9048623 ]],
 
        [[ 1.28737215, -6.51552529],
         [-9.92081893, -1.05985511]],
 
        [[ 8.53265156,  1.65726111],
         [ 3.21406123, -9.45604106]]])>,
 <tf.Tensor: shape=(4, 2, 1), dtype=float64, numpy=
 array([[[-5.86720335],
         [-9.61098953]],
 
        [[ 8.54644893],
         [-6.15847763]],
 
        [[-9.22646899],
         [-5.39704617]],
 
        [[ 9.79532013],
         [-1.55242791]]])>]

## 結合する

### 次元(添字)を増やさず結合する

以下の条件が必要:
- 型が一致している
- 結合する axis 以外が一致している

In [11]:
tf.concat([a_tensor, b_tensor], axis=0)

<tf.Tensor: shape=(5, 2, 3), dtype=float64, numpy=
array([[[ 1.73369404,  2.11681321, -5.86720335],
        [-4.38655271, -2.11421878, -9.61098953]],

       [[-5.71577344, -8.67702183,  8.54644893],
        [-3.22580896, -2.9048623 , -6.15847763]],

       [[ 1.28737215, -6.51552529, -9.22646899],
        [-9.92081893, -1.05985511, -5.39704617]],

       [[ 8.53265156,  1.65726111,  9.79532013],
        [ 3.21406123, -9.45604106, -1.55242791]],

       [[ 1.        ,  3.        ,  5.        ],
        [ 7.        , 11.        , 13.        ]]])>

## 縮小する

ｔｆ.extend_dim の逆は tf.squeeze

In [12]:
tf.squeeze(tf.expand_dims(a_tensor, axis=2))

<tf.Tensor: shape=(4, 2, 3), dtype=float64, numpy=
array([[[ 1.73369404,  2.11681321, -5.86720335],
        [-4.38655271, -2.11421878, -9.61098953]],

       [[-5.71577344, -8.67702183,  8.54644893],
        [-3.22580896, -2.9048623 , -6.15847763]],

       [[ 1.28737215, -6.51552529, -9.22646899],
        [-9.92081893, -1.05985511, -5.39704617]],

       [[ 8.53265156,  1.65726111,  9.79532013],
        [ 3.21406123, -9.45604106, -1.55242791]]])>