<a href="https://colab.research.google.com/github/applejxd/colaboratory/blob/master/DataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

## データ型の宣言

ndarray を1次元配列として扱う場合

In [ ]:
n1array = np.empty(5)
n1array[:] = [2, 3, 5, 7, 11]

print(type(n1array))
print(n1array.shape)
print(n1array)

<class 'numpy.ndarray'>
(5,)
[ 2.  3.  5.  7. 11.]


ndarray を2次元配列として扱う場合

In [ ]:
n2array = np.empty((2,3))
n2array[0,:] = [2, 3, 5]
n2array[1] = [1, 1, 2]

print(n2array.shape)
print(n2array)

(2, 3)
[[2. 3. 5.]
 [1. 1. 2.]]


Series（1次元配列）を扱う場合

In [ ]:
data1d = pd.Series(index=range(5), dtype=float)
data1d[:] = [1, 1, 2, 3, 5]
display(data1d)

0    1
1    1
2    2
3    3
4    5
dtype: int64

DataFrame(2次元配列)を扱う場合

In [ ]:
data2d = pd.DataFrame(index=range(5), columns=[], dtype=float)
data2d["Prime"] = [2, 3, 5, 7, 11]
data2d["Fibonacci"] = [1, 1, 2, 3, 5]
display(data2d)

Prime  Fibonacci
0      2          1
1      3          1
2      5          2
3      7          3
4     11          5

## 要素の格納と取り出し

ndarray はスライスによって格納指定・取り出しが可能

DataFrame の列名による指定

In [ ]:
data2d.loc[1:3, ["Prime"]]

Prime
1      3
2      5
3      7

DataFrame の行列番号による指定

In [ ]:
data2d.iloc[1:3, 1:]

Fibonacci
1          1
2          2