<a href="https://colab.research.google.com/github/applejxd/colaboratory/blob/master/DataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

## データ同士の変換

In [72]:
n2array = np.array([[2,3,5],[7,11,13]])
print(n2array)
print(type(pd.DataFrame(n2array)))
display(pd.DataFrame(n2array, index=range(2,4), columns=["A","B","C"]))

[[ 2  3  5]
 [ 7 11 13]]
<class 'pandas.core.frame.DataFrame'>


A   B   C
2  2   3   5
3  7  11  13

In [73]:
data1d = pd.Series([2,3,5,7,11], index=range(1,11,2))

print(data1d)
print(type(data1d.values))
print(data1d.values)

1     2
3     3
5     5
7     7
9    11
dtype: int64

<class 'numpy.ndarray'>
[ 2  3  5  7 11]


In [74]:
data2d = pd.DataFrame([[2,3,5],[7,11,13]], index=[4,2], columns=["A", "B", "C"])
display(data2d)
print(type(data2d.values))
print(data2d.values)

A   B   C
4  2   3   5
2  7  11  13

<class 'numpy.ndarray'>
[[ 2  3  5]
 [ 7 11 13]]


## 固定長データ型の宣言

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
42*np.ones((2,3))

array([[42., 42., 42.],
       [42., 42., 42.]])

In [28]:
display(pd.Series(42, index=range(5), dtype=int))

0    42
1    42
2    42
3    42
4    42
dtype: int64

In [29]:
display(pd.DataFrame(42, index=range(5), columns=["A", "B"], dtype=int))

A   B
0  42  42
1  42  42
2  42  42
3  42  42
4  42  42

## 可変長データ型の宣言

ndarray を1次元配列として扱う場合

In [6]:
n1array_1 = np.empty(0)
n1array_2 = np.empty(0)
for i in range(5):
    n1array_1 = np.append(n1array_1, i)
    n1array_2 = np.append(n1array_2, [i, 2*i])

print(type(n1array_1))
print(n1array_1)
print(n1array_2)

<class 'numpy.ndarray'>
[0. 1. 2. 3. 4.]
[0. 0. 1. 2. 2. 4. 3. 6. 4. 8.]


ndarray を2次元配列として扱う場合

In [18]:
n2array = np.empty((0, 3))
for i in range(4):
    n2array = np.append(n2array, [[i, 2*i, 3*i]], axis=0)

print(n2array.shape)
print(n2array)

(4, 3)
[[0. 0. 0.]
 [1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


Series（1次元配列）を扱う場合

In [33]:
data1d = pd.Series(dtype=int)
for i in range(5):
    data1d = data1d.append(pd.Series([i]))
display(data1d)

0    0
0    1
0    2
0    3
0    4
dtype: int64

DataFrame(2次元配列)を扱う場合

In [ ]:
data2d = pd.DataFrame(index=range(5), columns=[], dtype=float)
data2d["Prime"] = [2, 3, 5, 7, 11]
data2d["Fibonacci"] = [1, 1, 2, 3, 5]
display(data2d)

Prime  Fibonacci
0      2          1
1      3          1
2      5          2
3      7          3
4     11          5

## 要素の格納と取り出し

ndarray はスライスによって格納指定・取り出しが可能

In [78]:
n2array = np.zeros((5,7))
n2array[2:4, 3:7] = 42
print(n2array)
print(n2array[1:3, 2:5])

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 42. 42. 42. 42.]
 [ 0.  0.  0. 42. 42. 42. 42.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0. 42. 42.]]


DataFrame のラベル名による指定

In [89]:
data2d = pd.DataFrame(0, index=range(5), columns=["A", "B", "C"], dtype=int)
data2d.loc[1:3, ["B"]] = 42
display(data2d)
display(data2d.loc[2:4, ["B","C"]])

A   B  C
0  0   0  0
1  0  42  0
2  0  42  0
3  0  42  0
4  0   0  0

B  C
2  42  0
3  42  0
4   0  0

DataFrame の番号による指定

In [90]:
display(data2d.iloc[1:3, 1:])

B  C
1  42  0
2  42  0